version: "3.9"
services:

  webapp:
    build:
      context: .
    container_name: app
    volumes:
      - .:/usr/src/app
    env_file:
      - '.env'
    ports:
     - ${PORT}:${PORT}
    environment:
      PORT:  ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: ${MONGO_URL}
      REDIS_URL: ${REDIS_URL}
    networks:
      - default

  redis:
    image: redis
    container_name: redis
    volumes: 
      - ./dockerfiles/redis/cache:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    container_name: ${MONGO_HOST}
    ports:
      - ${MONGO_PORT}:27017
    volumes: 
      - ./dockerfiles/mongo/db:/data/db
    networks:
      - default
    restart: unless-stopped

networks:
  default: